"""Initial migration

Revision ID: 40bd08c89156
Revises: 
Create Date: 2024-04-14 02:26:12.088048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40bd08c89156'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exporttable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=100), nullable=False))

    with op.batch_alter_table('importtable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('importtable', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    with op.batch_alter_table('exporttable', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
